version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 170470708033.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t tdubey-firefox-test:latest .
      - docker tag tdubey-firefox-test:latest 170470708033.dkr.ecr.us-east-1.amazonaws.com/tdubey-firefox-test:latest
  post_build:
    commands:
      - docker push 170470708033.dkr.ecr.us-east-1.amazonaws.com/tdubey-firefox-test:latest